package Pop.Bot.Weapons;

import Pop.PopRandomizer;
import Pop.WeightedItem;
import Pop.WeightedItemCollection;

import java.util.ArrayList;
import java.util.Arrays;

public class WeaponModels {
    public static ArrayList<WeaponModel> WeaponModel = new ArrayList<>(Arrays.asList(
            // c models
            new WeaponModel("models/weapons/c_models/c_8mm_camera/c_8mm_camera.mdl"),
            new WeaponModel("models/weapons/c_models/c_ambassador/c_ambassador.mdl"),
            new WeaponModel("models/weapons/c_models/c_ambassador/c_ambassador_xmas.mdl"),
            new WeaponModel("models/weapons/c_models/c_axtinguisher/c_axtinguisher_pyro.mdl"),
            new WeaponModel("models/weapons/c_models/c_banana/c_banana.mdl"),
            new WeaponModel("models/weapons/c_models/c_bat.mdl"),
            new WeaponModel("models/weapons/c_models/c_bat/c_bat_xmas.mdl"),
            new WeaponModel("models/weapons/c_models/c_bonesaw/c_bonesaw.mdl"),
            new WeaponModel("models/weapons/c_models/c_bonesaw/c_bonesaw_xmas.mdl"),
            new WeaponModel("models/weapons/c_models/c_bottle/c_bottle.mdl"),
            new WeaponModel("models/weapons/c_models/c_bow/c_bow.mdl"),
            new WeaponModel("models/weapons/c_models/c_bow/c_bow_xmas.mdl"),
            new WeaponModel("models/weapons/c_models/c_boxing_gloves/c_boxing_gloves.mdl"),
            new WeaponModel("models/weapons/c_models/c_boxing_gloves/c_boxing_gloves_xmas.mdl"),
            new WeaponModel("models/weapons/c_models/c_buffbanner/c_buffbanner.mdl"),
            new WeaponModel("models/weapons/c_models/c_buffpack/c_buffpack.mdl"),
            new WeaponModel("models/weapons/c_models/c_buffpack/c_buffpack_xmas.mdl"),
            new WeaponModel("models/weapons/c_models/c_bugle/c_bugle.mdl"),
            new WeaponModel("models/weapons/c_models/c_builder/c_builder.mdl"),
            new WeaponModel("models/weapons/c_models/c_carnival_mallet/c_carnival_mallet.mdl"),
            new WeaponModel("models/weapons/c_models/c_claymore/c_claymore.mdl"),
            new WeaponModel("models/weapons/c_models/c_claymore/c_claymore_xmas.mdl"),
            new WeaponModel("models/weapons/c_models/c_csgo_awp/c_csgo_awp.mdl"),
            new WeaponModel("models/weapons/c_models/c_demo_arms.mdl"),
            new WeaponModel("models/weapons/c_models/c_directhit/c_directhit.mdl"),
            new WeaponModel("models/weapons/c_models/c_double_barrel.mdl"),
            new WeaponModel("models/weapons/c_models/c_energy_drink/c_energy_drink.mdl"),
            new WeaponModel("models/weapons/c_models/c_engineer_arms.mdl"),
            new WeaponModel("models/weapons/c_models/c_engineer_gunslinger.mdl"),
            new WeaponModel("models/weapons/c_models/c_fireaxe_pyro/c_fireaxe_pyro.mdl"),
            new WeaponModel("models/weapons/c_models/c_fireaxe_pyro/c_fireaxe_pyro_festivizer.mdl"),
            new WeaponModel("models/weapons/c_models/c_fireaxe_pyro/c_fireaxe_pyro_xmas.mdl"),
            new WeaponModel("models/weapons/c_models/c_flameball/c_flameball.mdl"),
            new WeaponModel("models/weapons/c_models/c_flameball/c_flameball_festivizer.mdl"),
            new WeaponModel("models/weapons/c_models/c_flamethrower/c_backburner.mdl"),
            new WeaponModel("models/weapons/c_models/c_flamethrower/c_backburner_xmas.mdl"),
            new WeaponModel("models/weapons/c_models/c_flamethrower/c_flamethrower.mdl"),
            new WeaponModel("models/weapons/c_models/c_flamethrower/c_flamethrower_festivizer.mdl"),
            new WeaponModel("models/weapons/c_models/c_flamethrower/c_flamethrower_pilotlight.mdl"),
            new WeaponModel("models/weapons/c_models/c_flamethrower/c_flamethrower_xmas.mdl"),
            new WeaponModel("models/weapons/c_models/c_flaregun_pyro/c_flaregun_pyro.mdl"),
            new WeaponModel("models/weapons/c_models/c_frontierjustice/c_frontierjustice.mdl"),
            new WeaponModel("models/weapons/c_models/c_frontierjustice/c_frontierjustice_xmas.mdl"),
            new WeaponModel("models/weapons/c_models/c_frying_pan/c_frying_pan.mdl"),
            new WeaponModel("models/weapons/c_models/c_gascan/c_gascan.mdl"),
            new WeaponModel("models/weapons/c_models/c_grapple_proj/c_grapple_proj.mdl"),
            new WeaponModel("models/weapons/c_models/c_grappling_hook/c_grappling_hook.mdl"),
            new WeaponModel("models/weapons/c_models/c_grenadelauncher/c_grenadelauncher.mdl"),
            new WeaponModel("models/weapons/c_models/c_grenadelauncher/c_grenadelauncher_festivizer.mdl"),
            new WeaponModel("models/weapons/c_models/c_grenadelauncher/c_grenadelauncher_xmas.mdl"),
            new WeaponModel("models/weapons/c_models/c_headtaker/c_headtaker.mdl"),
            new WeaponModel("models/weapons/c_models/c_heavy_arms.mdl"),
            new WeaponModel("models/weapons/c_models/c_hippocrates_bust/c_hippocrates_bust.mdl"),
            new WeaponModel("models/weapons/c_models/c_knife/c_knife.mdl"),
            new WeaponModel("models/weapons/c_models/c_knife/c_knife_festivizer.mdl"),
            new WeaponModel("models/weapons/c_models/c_knife/c_knife_xmas.mdl"),
            new WeaponModel("models/weapons/c_models/c_leechgun/c_leechgun.mdl"),
            new WeaponModel("models/weapons/c_models/c_lollichop/c_lollichop.mdl"),
            new WeaponModel("models/weapons/c_models/c_machete/c_machete.mdl"),
            new WeaponModel("models/weapons/c_models/c_machete/c_machete_festivizer.mdl"),
            new WeaponModel("models/weapons/c_models/c_medic_arms.mdl"),
            new WeaponModel("models/weapons/c_models/c_medigun/c_medigun.mdl"),
            new WeaponModel("models/weapons/c_models/c_medigun/c_medigun_festivizer.mdl"),
            new WeaponModel("models/weapons/c_models/c_medigun/c_medigun_xmas.mdl"),
            new WeaponModel("models/weapons/c_models/c_minigun/c_minigun.mdl"),
            new WeaponModel("models/weapons/c_models/c_minigun/c_minigun_festivizer.mdl"),
            new WeaponModel("models/weapons/c_models/c_minigun/c_minigun_natascha.mdl"),
            new WeaponModel("models/weapons/c_models/c_minigun/c_minigun_xmas.mdl"),
            new WeaponModel("models/weapons/c_models/c_overhealer/c_overhealer.mdl"),
            new WeaponModel("models/weapons/c_models/c_overhealer/c_overhealer_festivizer.mdl"),
            new WeaponModel("models/weapons/c_models/c_p2rec/c_p2rec.mdl"),
            new WeaponModel("models/weapons/c_models/c_pda_engineer/c_pda_engineer.mdl"),
            new WeaponModel("models/weapons/c_models/c_pickaxe/c_pickaxe.mdl"),
            new WeaponModel("models/weapons/c_models/c_pickaxe/c_pickaxe_s2.mdl"),
            new WeaponModel("models/weapons/c_models/c_pistol/c_pistol.mdl"),
            new WeaponModel("models/weapons/c_models/c_pistol/c_pistol_festivizer.mdl"),
            new WeaponModel("models/weapons/c_models/c_proto_backpack/c_proto_backpack.mdl"),
            new WeaponModel("models/weapons/c_models/c_proto_medigun/c_proto_medigun.mdl"),
            new WeaponModel("models/weapons/c_models/c_proto_medigun/c_proto_medigun_festivizer.mdl"),
            new WeaponModel("models/weapons/c_models/c_proto_syringegun/c_proto_syringegun.mdl"),
            new WeaponModel("models/weapons/c_models/c_pyro_arms.mdl"),
            new WeaponModel("models/weapons/c_models/c_rainblower/c_rainblower.mdl"),
            new WeaponModel("models/weapons/c_models/c_revolver/c_revolver.mdl"),
            new WeaponModel("models/weapons/c_models/c_revolver/c_revolver_festivizer.mdl"),
            new WeaponModel("models/weapons/c_models/c_revolver/c_revolver_xmas.mdl"),
            new WeaponModel("models/weapons/c_models/c_rocketjumper/c_rocketjumper.mdl"),
            new WeaponModel("models/weapons/c_models/c_rocketlauncher/c_rocketlauncher.mdl"),
            new WeaponModel("models/weapons/c_models/c_rocketlauncher/c_rocketlauncher_festivizer.mdl"),
            new WeaponModel("models/weapons/c_models/c_rocketlauncher/c_rocketlauncher_xmas.mdl"),
            new WeaponModel("models/weapons/c_models/c_rocketpack/c_rocketpack.mdl"),
            new WeaponModel("models/weapons/c_models/c_sandwich/c_robo_sandwich.mdl"),
            new WeaponModel("models/weapons/c_models/c_sandwich/c_sandwich.mdl"),
            new WeaponModel("models/weapons/c_models/c_sandwich/c_sandwich_xmas.mdl"),
            new WeaponModel("models/weapons/c_models/c_sapper/c_sapper.mdl"),
            new WeaponModel("models/weapons/c_models/c_sapper/c_sapper_xmas.mdl"),
            new WeaponModel("models/weapons/c_models/c_saxxy/c_saxxy.mdl", "Saxxy", true),
            new WeaponModel("models/weapons/c_models/c_scattergun.mdl"),
            new WeaponModel("models/weapons/c_models/c_scattergun/c_scattergun_festivizer.mdl"),
            new WeaponModel("models/weapons/c_models/c_scattergun/c_scattergun_xmas.mdl"),
            new WeaponModel("models/weapons/c_models/c_scottish_resistance/c_scottish_resistance.mdl"),
            new WeaponModel("models/weapons/c_models/c_scottish_resistance/c_scottish_resistance_festivizer.mdl"),
            new WeaponModel("models/weapons/c_models/c_scout_arms.mdl"),
            new WeaponModel("models/weapons/c_models/c_shotgun/c_shotgun.mdl"),
            new WeaponModel("models/weapons/c_models/c_shotgun/c_shotgun_festivizer.mdl"),
            new WeaponModel("models/weapons/c_models/c_shotgun/c_shotgun_xmas.mdl"),
            new WeaponModel("models/weapons/c_models/c_shovel/c_shovel.mdl"),
            new WeaponModel("models/weapons/c_models/c_shovel/c_shovel_festivizer.mdl"),
            new WeaponModel("models/weapons/c_models/c_slapping_glove/c_slapping_glove.mdl"),
            new WeaponModel("models/weapons/c_models/c_slapping_glove/w_slapping_glove.mdl"),
            new WeaponModel("models/weapons/c_models/c_smg/c_smg.mdl"),
            new WeaponModel("models/weapons/c_models/c_smg/c_smg_festivizer.mdl"),
            new WeaponModel("models/weapons/c_models/c_smg/c_smg_xmas.mdl"),
            new WeaponModel("models/weapons/c_models/c_sniper_arms.mdl"),
            new WeaponModel("models/weapons/c_models/c_sniperrifle/c_sniperrifle.mdl"),
            new WeaponModel("models/weapons/c_models/c_sniperrifle/c_sniperrifle_festivizer.mdl"),
            new WeaponModel("models/weapons/c_models/c_sniperrifle/c_sniperrifle_xmas.mdl"),
            new WeaponModel("models/weapons/c_models/c_soldier_arms.mdl"),
            new WeaponModel("models/weapons/c_models/c_spy_arms.mdl"),
            new WeaponModel("models/weapons/c_models/c_sticky_jumper/c_sticky_jumper.mdl"),
            new WeaponModel("models/weapons/c_models/c_stickybomb_launcher/c_stickybomb_launcher.mdl"),
            new WeaponModel("models/weapons/c_models/c_stickybomb_launcher/c_stickybomb_launcher_festivizer.mdl"),
            new WeaponModel("models/weapons/c_models/c_stickybomb_launcher/c_stickybomb_launcher_xmas.mdl"),
            new WeaponModel("models/weapons/c_models/c_syringegun/c_syringegun.mdl"),
            new WeaponModel("models/weapons/c_models/c_targe/c_targe.mdl"),
            new WeaponModel("models/weapons/c_models/c_targe/c_targe_xmas.mdl"),
            new WeaponModel("models/weapons/c_models/c_tfc_sniperrifle/c_tfc_sniperrifle.mdl"),
            new WeaponModel("models/weapons/c_models/c_toolbox/c_toolbox.mdl"),
            new WeaponModel("models/weapons/c_models/c_ubersaw/c_ubersaw.mdl"),
            new WeaponModel("models/weapons/c_models/c_ubersaw/c_ubersaw_festivizer.mdl"),
            new WeaponModel("models/weapons/c_models/c_ubersaw/c_ubersaw_xmas.mdl"),
            new WeaponModel("models/weapons/c_models/c_wooden_bat/c_wooden_bat.mdl"),
            new WeaponModel("models/weapons/c_models/c_wooden_bat/c_wooden_bat_festivizer.mdl"),
            new WeaponModel("models/weapons/c_models/c_wrangler.mdl"),
            new WeaponModel("models/weapons/c_models/c_wrangler_xmas.mdl"),
            new WeaponModel("models/weapons/c_models/c_wrench/c_wrench.mdl"),
            new WeaponModel("models/weapons/c_models/c_wrench/c_wrench_festivizer.mdl"),
            new WeaponModel("models/weapons/c_models/c_wrench/c_wrench_xmas.mdl"),
            new WeaponModel("models/weapons/c_models/c_xms_double_barrel.mdl"),
            new WeaponModel("models/weapons/c_models/c_xms_energy_drink/c_xms_energy_drink.mdl"),
            new WeaponModel("models/weapons/c_models/c_xms_festive_ornament.mdl"),
            new WeaponModel("models/weapons/c_models/c_xms_flaregun/c_xms_flaregun.mdl"),
            new WeaponModel("models/weapons/c_models/c_xms_urinejar.mdl"),
            new WeaponModel("models/weapons/c_models/stattrack.mdl"),
            new WeaponModel("models/weapons/c_models/urinejar.mdl"),

            // workshop c models
            new WeaponModel("models/workshop/weapons/c_models/c_acr_hookblade/c_acr_hookblade.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_amputator/c_amputator.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_atom_launcher/c_atom_launcher.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_ava_roseknife/c_ava_roseknife.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_back_scratcher/c_back_scratcher.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_battalion_buffbanner/c_battalion_buffbanner.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_battalion_buffpack/c_battalion_buffpack.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_battalion_bugle/c_battalion_bugle.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_battleaxe/c_battleaxe.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_bazaar_sniper/c_bazaar_sniper.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_bear_claw/c_bear_claw.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_blackbox/c_blackbox.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_blackbox/c_blackbox_xmas.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_bonk_bat/c_bonk_bat.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_boston_basher/c_boston_basher.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_buffalo_steak/c_buffalo_steak.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_buffalo_steak/plate_buffalo_steak.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_caber/c_caber.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_caber/c_caber_exploded.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_candy_cane/c_candy_cane.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_chocolate/c_chocolate.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_chocolate/plate_chocolate.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_claidheamohmor/c_claidheamohmor.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_croc_knife/c_croc_knife.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_crossing_guard/c_crossing_guard.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_crusaders_crossbow/c_crusaders_crossbow.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_crusaders_crossbow/c_crusaders_crossbow_xmas.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_degreaser/c_degreaser.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_degreaser/c_degreaser_pilotlight.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_demo_cannon/c_demo_cannon.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_demo_sultan_sword/c_demo_sultan_sword.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_detonator/c_detonator.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_drg_cowmangler/c_drg_cowmangler.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_drg_manmelter/c_drg_manmelter.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_drg_phlogistinator/c_drg_phlogistinator.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_drg_pomson/c_drg_pomson.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_drg_righteousbison/c_drg_righteousbison.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_drg_thirddegree/c_drg_thirddegree.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_drg_wrenchmotron/c_drg_wrenchmotron.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_dumpster_device/c_dumpster_device.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_eternal_reward/c_eternal_reward.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_eviction_notice/c_eviction_notice.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_fishcake/c_fishcake.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_fishcake/plate_fishcake.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_fists_of_steel/c_fists_of_steel.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_gatling_gun/c_gatling_gun.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_golfclub/c_golfclub.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_ham/c_ham.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_holymackerel/c_holymackerel.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_holymackerel/c_holymackerel_xmas.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_invasion_bat/c_invasion_bat.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_invasion_pistol/c_invasion_pistol.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_invasion_sniperrifle/c_invasion_sniperrifle.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_invasion_wrangler/c_invasion_wrangler.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_iron_curtain/c_iron_curtain.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_jag/c_jag.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_kingmaker_sticky/c_kingmaker_sticky.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_kingmaker_sticky/w_kingmaker_stickybomb.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_letranger/c_letranger.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_liberty_launcher/c_liberty_launcher.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_lochnload/c_lochnload.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_madmilk/c_madmilk.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_mailbox/c_mailbox.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_market_gardener/c_market_gardener.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_medigun_defense/c_medigun_defense.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_medigun_defense/c_medigun_defensepack.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_paintrain/c_paintrain.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_paratooper_pack/c_paratrooper_pack.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_paratooper_pack/c_paratrooper_pack_open.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_paratooper_pack/c_paratrooper_parachute.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_pep_pistol/c_pep_pistol.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_pep_scattergun/c_pep_scattergun.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_persian_shield/c_persian_shield.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_persian_shield/c_persian_shield_all.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_persian_shield/c_persian_shield_arrow.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_persian_shield/c_persian_shield_spike.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_picket/c_picket.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_powerjack/c_powerjack.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_pro_rifle/c_pro_rifle.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_pro_smg/c_pro_smg.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_quadball/c_quadball.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_quadball/w_quadball_grenade.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_reserve_shooter/c_reserve_shooter.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_rfa_hammer/c_rfa_hammer.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_riding_crop/c_riding_crop.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_rift_fire_axe/c_rift_fire_axe.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_rift_fire_mace/c_rift_fire_mace.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_russian_riot/c_russian_riot.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_scatterdrum/c_scatterdrum.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_scimitar/c_scimitar.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_scorch_shot/c_scorch_shot.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_scotland_shard/c_scotland_shard.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_scout_sword/c_scout_sword.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_shortstop/c_shortstop.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_skullbat/c_skullbat.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_sledgehammer/c_sledgehammer.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_snub_nose/c_snub_nose.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_soda_popper/c_soda_popper.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_spikewrench/c_spikewrench.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_sr3_punch/c_sr3_punch.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_switchblade/c_switchblade.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_sydney_sleeper/c_sydney_sleeper.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_tele_shotgun/c_tele_shotgun.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_tele_shotgun/c_tele_shotgun_screen.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_tomislav/c_tomislav.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_trenchgun/c_trenchgun.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_ttg_max_gun/c_ttg_max_gun.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_ttg_sam_gun/c_ttg_sam_gun.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_uberneedle/c_uberneedle.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_unarmed_combat/c_unarmed_combat.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_voodoo_pin/c_voodoo_pin.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_wheel_shield/c_wheel_shield.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_winger_pistol/c_winger_pistol.mdl", "Winger"),
            new WeaponModel("models/workshop/weapons/c_models/c_wood_machete/c_wood_machete.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_xms_cold_shoulder/c_xms_cold_shoulder.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_xms_giftwrap/c_xms_giftwrap.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_xms_gloves/c_xms_gloves.mdl"),

            // sappers
            new WeaponModel("models/buildables/p2rec_placed.mdl"),
            new WeaponModel("models/buildables/p2rec_placement.mdl"),
            new WeaponModel("models/buildables/sapper_placed.mdl"),
            new WeaponModel("models/buildables/sapper_placement.mdl"),
            new WeaponModel("models/buildables/sapper_xmas_placed.mdl"),
            new WeaponModel("models/buildables/sapper_xmas_placement.mdl"),
            new WeaponModel("models/buildables/sd_sapper_placed.mdl"),
            new WeaponModel("models/buildables/sd_sapper_placement.mdl"),


            // canteens
            new WeaponModel("models/player/items/mvm_loot/all_class/mvm_flask_ammo.mdl"),
            new WeaponModel("models/player/items/mvm_loot/all_class/mvm_flask_build.mdl"),
            new WeaponModel("models/player/items/mvm_loot/all_class/mvm_flask_generic.mdl"),
            new WeaponModel("models/player/items/mvm_loot/all_class/mvm_flask_krit.mdl"),
            new WeaponModel("models/player/items/mvm_loot/all_class/mvm_flask_tele.mdl"),
            new WeaponModel("models/player/items/mvm_loot/all_class/mvm_flask_uber.mdl")
    ));

    public static ArrayList<WeaponModel> cosmeticModels = new ArrayList<>(Arrays.asList(
            // botkiller fobs
            new WeaponModel("models/player/items/mvm_loot/demo/fob_e_stickybomb.mdl"),
            new WeaponModel("models/player/items/mvm_loot/demo/fob_h_stickybomb.mdl"),
            new WeaponModel("models/player/items/mvm_loot/demo/fob_h_stickybomb_diamond.mdl"),
            new WeaponModel("models/player/items/mvm_loot/engineer/fob_e_wrench.mdl"),
            new WeaponModel("models/player/items/mvm_loot/engineer/fob_h_wrench.mdl"),
            new WeaponModel("models/player/items/mvm_loot/engineer/fob_h_wrench_diamond.mdl"),
            new WeaponModel("models/player/items/mvm_loot/heavy/fob_e_minigun.mdl"),
            new WeaponModel("models/player/items/mvm_loot/heavy/fob_h_minigun.mdl"),
            new WeaponModel("models/player/items/mvm_loot/heavy/fob_h_minigun_diamond.mdl"),
            new WeaponModel("models/player/items/mvm_loot/medic/fob_e_medigun.mdl"),
            new WeaponModel("models/player/items/mvm_loot/medic/fob_h_medigun.mdl"),
            new WeaponModel("models/player/items/mvm_loot/medic/fob_h_medigun_diamond.mdl"),
            new WeaponModel("models/player/items/mvm_loot/pyro/fob_e_flamethrower.mdl"),
            new WeaponModel("models/player/items/mvm_loot/pyro/fob_e_flamethrower_v.mdl"),
            new WeaponModel("models/player/items/mvm_loot/pyro/fob_h_flamethrower.mdl"),
            new WeaponModel("models/player/items/mvm_loot/pyro/fob_h_flamethrower_diamond.mdl"),
            new WeaponModel("models/player/items/mvm_loot/pyro/fob_h_flamethrower_diamond_v.mdl"),
            new WeaponModel("models/player/items/mvm_loot/pyro/fob_h_flamethrower_v.mdl"),
            new WeaponModel("models/player/items/mvm_loot/scout/fob_e_scattergun.mdl"),
            new WeaponModel("models/player/items/mvm_loot/scout/fob_h_scattergun.mdl"),
            new WeaponModel("models/player/items/mvm_loot/scout/fob_h_scattergun_diamond.mdl"),
            new WeaponModel("models/player/items/mvm_loot/sniper/fob_e_sniperrifle.mdl"),
            new WeaponModel("models/player/items/mvm_loot/sniper/fob_h_sniperrifle.mdl"),
            new WeaponModel("models/player/items/mvm_loot/sniper/fob_h_sniperrifle_diamond.mdl"),
            new WeaponModel("models/player/items/mvm_loot/soldier/fob_e_rocketlauncher.mdl"),
            new WeaponModel("models/player/items/mvm_loot/soldier/fob_h_rocketlauncher.mdl"),
            new WeaponModel("models/player/items/mvm_loot/soldier/fob_h_rocketlauncher_diamond.mdl"),
            new WeaponModel("models/player/items/mvm_loot/spy/fob_e_knife.mdl"),
            new WeaponModel("models/player/items/mvm_loot/spy/fob_h_knife.mdl"),
            new WeaponModel("models/player/items/mvm_loot/spy/fob_h_knife_diamond.mdl"),

            // items
            new WeaponModel("models/workshop/player/items/demo/bagpipes/bagpipes.mdl"),
            new WeaponModel("models/workshop/player/items/demo/demo_booties/demo_booties.mdl"),
            new WeaponModel("models/workshop/player/items/demo/pegleg/pegleg.mdl"),
            new WeaponModel("models/workshop/player/items/engineer/bucking_bronco/bucking_bronco.mdl"),
            new WeaponModel("models/workshop/player/items/pyro/ghost_aspect/ghost_aspect.mdl"),
            new WeaponModel("models/workshop/player/items/pyro/pyro_halloween_gasmask/pyro_halloween_gasmask.mdl"),
            new WeaponModel("models/workshop/player/items/pyro/spring_rider/spring_rider.mdl"),
            new WeaponModel("models/workshop/player/items/pyro/threea_nabler/threea_nabler.mdl"),
            new WeaponModel("models/workshop/player/items/sniper/croc_shield/croc_shield.mdl"),
            new WeaponModel("models/workshop/player/items/sniper/killer_solo/killer_solo.mdl"),
            new WeaponModel("models/workshop/player/items/sniper/xms_sniper_commandobackpack/xms_sniper_commandobackpack.mdl"),
            new WeaponModel("models/workshop/player/items/soldier/fumblers_fanfare/fumblers_fanfare.mdl"),
            new WeaponModel("models/workshop/player/items/soldier/mantreads/mantreads.mdl"),

            // misc
            new WeaponModel("models/player/items/all_class/drg_badge.mdl"),
            new WeaponModel("models/player/items/all_class/hwn_spellbook_complete.mdl"),
            new WeaponModel("models/player/items/all_class/hwn_spellbook_diary.mdl"),
            new WeaponModel("models/player/items/all_class/ring_demo.mdl"),
            new WeaponModel("models/player/items/all_class/ring_Engineer.mdl"),
            new WeaponModel("models/player/items/all_class/ring_Heavy.mdl"),
            new WeaponModel("models/player/items/all_class/ring_Medic.mdl"),
            new WeaponModel("models/player/items/all_class/ring_Pyro.mdl"),
            new WeaponModel("models/player/items/all_class/ring_Scout.mdl"),
            new WeaponModel("models/player/items/all_class/ring_Sniper.mdl"),
            new WeaponModel("models/player/items/all_class/ring_Soldier.mdl"),
            new WeaponModel("models/player/items/all_class/ring_Spy.mdl"),
            new WeaponModel("models/player/items/crafting/coin_invasion.mdl"),
            new WeaponModel("models/player/items/crafting/coin_summer2015_bronze.mdl"),
            new WeaponModel("models/player/items/crafting/coin_summer2015_gold.mdl"),
            new WeaponModel("models/player/items/crafting/coin_summer2015_gravel.mdl"),
            new WeaponModel("models/player/items/crafting/coin_summer2015_silver.mdl"),
            new WeaponModel("models/player/items/crafting/community_cosmetic_case.mdl"),
            new WeaponModel("models/player/items/crafting/cosmetic_case.mdl"),
            new WeaponModel("models/player/items/crafting/cosmetic_case_ribbon.mdl"),
            new WeaponModel("models/player/items/crafting/halloween_case.mdl"),
            new WeaponModel("models/player/items/crafting/halloween2015_case.mdl"),
            new WeaponModel("models/player/items/crafting/stamp_winter2016.mdl"),
            new WeaponModel("models/player/items/crafting/weapons_case.mdl"),
            new WeaponModel("models/player/items/cyoa_pda/cyoa_pda.mdl"),
            new WeaponModel("models/player/items/demo/crown.mdl"),
            new WeaponModel("models/player/items/engineer/guitar.mdl"),
            new WeaponModel("models/workshop/player/items/all_class/secondrate_sorcery/secondrate_sorcery_demo.mdl"),
            new WeaponModel("models/workshop/player/items/all_class/zoomin_broom/zoomin_broom_demo.mdl")
    ));

    public static ArrayList<WeaponModel> buildingModels = new ArrayList<>(Arrays.asList(
            new WeaponModel("models/buildables/dispenser.mdl"),
            new WeaponModel("models/buildables/dispenser_lvl2.mdl"),
            new WeaponModel("models/buildables/dispenser_lvl3.mdl"),
            new WeaponModel("models/buildables/sentry1.mdl"),
            new WeaponModel("models/buildables/sentry1_heavy.mdl"),
            new WeaponModel("models/buildables/sentry2.mdl"),
            new WeaponModel("models/buildables/sentry2_heavy.mdl"),
            new WeaponModel("models/buildables/sentry3.mdl"),
            new WeaponModel("models/buildables/sentry3_heavy.mdl"),
            new WeaponModel("models/buildables/sentry3_rockets.mdl"),
            new WeaponModel("models/buildables/teleporter.mdl"),
            new WeaponModel("models/buildables/teleporter_blueprint_enter.mdl"),
            new WeaponModel("models/buildables/teleporter_blueprint_exit.mdl")
    ));

    public static ArrayList<WeaponModel> breadModels = new ArrayList<>(Arrays.asList(
            new WeaponModel("models/weapons/c_models/c_bread/c_bread_baguette.mdl"),
            new WeaponModel("models/weapons/c_models/c_bread/c_bread_burnt.mdl"),
            new WeaponModel("models/weapons/c_models/c_bread/c_bread_cinnamon.mdl"),
            new WeaponModel("models/weapons/c_models/c_bread/c_bread_cornbread.mdl"),
            new WeaponModel("models/weapons/c_models/c_bread/c_bread_crumpet.mdl"),
            new WeaponModel("models/weapons/c_models/c_bread/c_bread_plainloaf.mdl"),
            new WeaponModel("models/weapons/c_models/c_bread/c_bread_pretzel.mdl"),
            new WeaponModel("models/weapons/c_models/c_bread/c_bread_ration.mdl"),
            new WeaponModel("models/weapons/c_models/c_bread/c_bread_russianblack.mdl"),
            new WeaponModel("models/weapons/w_models/w_breadmonster/w_breadmonster.mdl"),
            new WeaponModel("models/weapons/c_models/c_breadmonster/c_breadmonster.mdl"),
            new WeaponModel("models/weapons/c_models/c_breadmonster/c_breadmonster_milk.mdl"),
            new WeaponModel("models/weapons/c_models/c_breadmonster_gloves/c_breadmonster_gloves.mdl"),
            new WeaponModel("models/weapons/c_models/c_breadmonster_sapper/c_breadmonster_sapper.mdl")
    ));

    public static ArrayList<WeaponModel> pickupsAndFunGibModels = new ArrayList<>(Arrays.asList(
            new WeaponModel("models/items/ammopack_large.mdl"),
            new WeaponModel("models/items/ammopack_large_bday.mdl"),
            new WeaponModel("models/items/ammopack_medium.mdl"),
            new WeaponModel("models/items/ammopack_medium_bday.mdl"),
            new WeaponModel("models/items/ammopack_small.mdl"),
            new WeaponModel("models/items/banana/plate_banana.mdl"),
            new WeaponModel("models/items/currencypack_large.mdl"),
            new WeaponModel("models/items/currencypack_medium.mdl"),
            new WeaponModel("models/items/currencypack_small.mdl"),
            new WeaponModel("models/items/festivizer.mdl"),
            new WeaponModel("models/items/gift_festive.mdl"),
            new WeaponModel("models/items/medkit_large.mdl"),
            new WeaponModel("models/items/medkit_large_bday.mdl"),
            new WeaponModel("models/items/medkit_medium.mdl"),
            new WeaponModel("models/items/medkit_medium_bday.mdl"),
            new WeaponModel("models/items/medkit_small.mdl"),
            new WeaponModel("models/items/paintkit_tool.mdl"),
            new WeaponModel("models/items/plate.mdl"),
            new WeaponModel("models/items/plate_robo_sandwich.mdl"),
            new WeaponModel("models/items/plate_sandwich_xmas.mdl"),
            new WeaponModel("models/passtime/ball/passtime_ball.mdl"),
            new WeaponModel("models/player/gibs/gibs_balloon.mdl"),
            new WeaponModel("models/player/gibs/gibs_bolt.mdl"),
            new WeaponModel("models/player/gibs/gibs_boot.mdl"),
            new WeaponModel("models/player/gibs/gibs_burger.mdl"),
            new WeaponModel("models/player/gibs/gibs_can.mdl"),
            new WeaponModel("models/player/gibs/gibs_clock.mdl"),
            new WeaponModel("models/player/gibs/gibs_fish.mdl"),
            new WeaponModel("models/player/gibs/gibs_gear1.mdl"),
            new WeaponModel("models/player/gibs/gibs_gear2.mdl"),
            new WeaponModel("models/player/gibs/gibs_gear3.mdl"),
            new WeaponModel("models/player/gibs/gibs_gear4.mdl"),
            new WeaponModel("models/player/gibs/gibs_gear5.mdl"),
            new WeaponModel("models/player/gibs/gibs_hubcap.mdl"),
            new WeaponModel("models/player/gibs/gibs_licenseplate.mdl"),
            new WeaponModel("models/player/gibs/gibs_spring1.mdl"),
            new WeaponModel("models/player/gibs/gibs_spring2.mdl"),
            new WeaponModel("models/player/gibs/gibs_teeth.mdl"),
            new WeaponModel("models/player/gibs/gibs_tire.mdl"),
            new WeaponModel("models/player/gibs/random_organ.mdl"),
            new WeaponModel("models/player/gibs/random_organ.mdl"),
            new WeaponModel("models/workshop/cases/invasion_case/invasion_case.mdl"),
            new WeaponModel("models/workshop/cases/invasion_case/invasion_case_rare.mdl"),
            new WeaponModel("models/weapons/w_models/w_toolbox.mdl")
    ));

    public static ArrayList<WeaponModel> projectileModels = new ArrayList<>(Arrays.asList(
            new WeaponModel("models/weapons/w_models/w_arrow.mdl"),
            new WeaponModel("models/weapons/w_models/w_arrow_xmas.mdl"),
            new WeaponModel("models/weapons/w_models/w_baseball.mdl"),
            new WeaponModel("models/weapons/w_models/w_cannonball.mdl"),
            new WeaponModel("models/weapons/w_models/w_cigarette_case.mdl"),
            new WeaponModel("models/weapons/w_models/w_drg_ball.mdl"),
            new WeaponModel("models/weapons/w_models/w_flaregun_shell.mdl"),
            new WeaponModel("models/weapons/w_models/w_grenade_grenadelauncher.mdl"),
            new WeaponModel("models/weapons/w_models/w_grenadelauncher.mdl"),
            new WeaponModel("models/weapons/w_models/w_repair_claw.mdl"),
            new WeaponModel("models/weapons/w_models/w_rocket.mdl"),
            new WeaponModel("models/weapons/w_models/w_rocket_airstrike/w_rocket_airstrike.mdl"),
            new WeaponModel("models/weapons/w_models/w_stickybomb.mdl"),
            new WeaponModel("models/weapons/w_models/w_stickybomb_d.mdl"),
            new WeaponModel("models/weapons/w_models/w_stickybomb2.mdl"),
            new WeaponModel("models/weapons/w_models/w_syringe_proj.mdl"),
            new WeaponModel("models/workshop/weapons/c_models/c_crusaders_crossbow/c_crusaders_crossbow_xmas_proj.mdl")
    ));

    /**
     * Gets a random model using the defined lists, which have their own weights
     * @return The random model chosen
     */
    public static WeaponModel getRandomModel() {
        ArrayList<WeightedItem<ArrayList<WeaponModel>>> weightedItems = new ArrayList<>(Arrays.asList(
            new WeightedItem<>(WeaponModel, 100),
            new WeightedItem<>(cosmeticModels, 100),
            new WeightedItem<>(breadModels, 200),
            new WeightedItem<>(pickupsAndFunGibModels, 200),
            new WeightedItem<>(projectileModels, 150),
            new WeightedItem<>(buildingModels, 80)
        ));

        WeightedItemCollection<ArrayList<WeaponModel>> collection = new WeightedItemCollection<>(weightedItems);
        return PopRandomizer.randomElement(collection.getRandomItem());
    }
}
