package Pop.Bot;

import Pop.PopRandomizer;
import Pop.WeightedItem;
import Pop.WeightedItemCollection;

import java.util.ArrayList;
import java.util.Arrays;

public class WeaponModels {
    public static ArrayList<String> weaponModels = new ArrayList<>(Arrays.asList(
        // c models
        "models/weapons/c_models/c_8mm_camera/c_8mm_camera.mdl",
        "models/weapons/c_models/c_ambassador/c_ambassador.mdl",
        "models/weapons/c_models/c_ambassador/c_ambassador_xmas.mdl",
        "models/weapons/c_models/c_axtinguisher/c_axtinguisher_pyro.mdl",
        "models/weapons/c_models/c_banana/c_banana.mdl",
        "models/weapons/c_models/c_bat.mdl",
        "models/weapons/c_models/c_bat/c_bat_xmas.mdl",
        "models/weapons/c_models/c_bonesaw/c_bonesaw.mdl",
        "models/weapons/c_models/c_bonesaw/c_bonesaw_xmas.mdl",
        "models/weapons/c_models/c_bottle/c_bottle.mdl",
        "models/weapons/c_models/c_bow/c_bow.mdl",
        "models/weapons/c_models/c_bow/c_bow_xmas.mdl",
        "models/weapons/c_models/c_boxing_gloves/c_boxing_gloves.mdl",
        "models/weapons/c_models/c_boxing_gloves/c_boxing_gloves_xmas.mdl",
        "models/weapons/c_models/c_buffbanner/c_buffbanner.mdl",
        "models/weapons/c_models/c_buffpack/c_buffpack.mdl",
        "models/weapons/c_models/c_buffpack/c_buffpack_xmas.mdl",
        "models/weapons/c_models/c_bugle/c_bugle.mdl",
        "models/weapons/c_models/c_builder/c_builder.mdl",
        "models/weapons/c_models/c_carnival_mallet/c_carnival_mallet.mdl",
        "models/weapons/c_models/c_claymore/c_claymore.mdl",
        "models/weapons/c_models/c_claymore/c_claymore_xmas.mdl",
        "models/weapons/c_models/c_csgo_awp/c_csgo_awp.mdl",
        "models/weapons/c_models/c_demo_arms.mdl",
        "models/weapons/c_models/c_directhit/c_directhit.mdl",
        "models/weapons/c_models/c_double_barrel.mdl",
        "models/weapons/c_models/c_energy_drink/c_energy_drink.mdl",
        "models/weapons/c_models/c_engineer_arms.mdl",
        "models/weapons/c_models/c_engineer_gunslinger.mdl",
        "models/weapons/c_models/c_fireaxe_pyro/c_fireaxe_pyro.mdl",
        "models/weapons/c_models/c_fireaxe_pyro/c_fireaxe_pyro_festivizer.mdl",
        "models/weapons/c_models/c_fireaxe_pyro/c_fireaxe_pyro_xmas.mdl",
        "models/weapons/c_models/c_flameball/c_flameball.mdl",
        "models/weapons/c_models/c_flameball/c_flameball_festivizer.mdl",
        "models/weapons/c_models/c_flamethrower/c_backburner.mdl",
        "models/weapons/c_models/c_flamethrower/c_backburner_xmas.mdl",
        "models/weapons/c_models/c_flamethrower/c_flamethrower.mdl",
        "models/weapons/c_models/c_flamethrower/c_flamethrower_festivizer.mdl",
        "models/weapons/c_models/c_flamethrower/c_flamethrower_pilotlight.mdl",
        "models/weapons/c_models/c_flamethrower/c_flamethrower_xmas.mdl",
        "models/weapons/c_models/c_flaregun_pyro/c_flaregun_pyro.mdl",
        "models/weapons/c_models/c_frontierjustice/c_frontierjustice.mdl",
        "models/weapons/c_models/c_frontierjustice/c_frontierjustice_xmas.mdl",
        "models/weapons/c_models/c_frying_pan/c_frying_pan.mdl",
        "models/weapons/c_models/c_gascan/c_gascan.mdl",
        "models/weapons/c_models/c_grapple_proj/c_grapple_proj.mdl",
        "models/weapons/c_models/c_grappling_hook/c_grappling_hook.mdl",
        "models/weapons/c_models/c_grenadelauncher/c_grenadelauncher.mdl",
        "models/weapons/c_models/c_grenadelauncher/c_grenadelauncher_festivizer.mdl",
        "models/weapons/c_models/c_grenadelauncher/c_grenadelauncher_xmas.mdl",
        "models/weapons/c_models/c_headtaker/c_headtaker.mdl",
        "models/weapons/c_models/c_heavy_arms.mdl",
        "models/weapons/c_models/c_hippocrates_bust/c_hippocrates_bust.mdl",
        "models/weapons/c_models/c_knife/c_knife.mdl",
        "models/weapons/c_models/c_knife/c_knife_festivizer.mdl",
        "models/weapons/c_models/c_knife/c_knife_xmas.mdl",
        "models/weapons/c_models/c_leechgun/c_leechgun.mdl",
        "models/weapons/c_models/c_lollichop/c_lollichop.mdl",
        "models/weapons/c_models/c_machete/c_machete.mdl",
        "models/weapons/c_models/c_machete/c_machete_festivizer.mdl",
        "models/weapons/c_models/c_medic_arms.mdl",
        "models/weapons/c_models/c_medigun/c_medigun.mdl",
        "models/weapons/c_models/c_medigun/c_medigun_festivizer.mdl",
        "models/weapons/c_models/c_medigun/c_medigun_xmas.mdl",
        "models/weapons/c_models/c_minigun/c_minigun.mdl",
        "models/weapons/c_models/c_minigun/c_minigun_festivizer.mdl",
        "models/weapons/c_models/c_minigun/c_minigun_natascha.mdl",
        "models/weapons/c_models/c_minigun/c_minigun_xmas.mdl",
        "models/weapons/c_models/c_overhealer/c_overhealer.mdl",
        "models/weapons/c_models/c_overhealer/c_overhealer_festivizer.mdl",
        "models/weapons/c_models/c_p2rec/c_p2rec.mdl",
        "models/weapons/c_models/c_pda_engineer/c_pda_engineer.mdl",
        "models/weapons/c_models/c_pickaxe/c_pickaxe.mdl",
        "models/weapons/c_models/c_pickaxe/c_pickaxe_s2.mdl",
        "models/weapons/c_models/c_pistol/c_pistol.mdl",
        "models/weapons/c_models/c_pistol/c_pistol_festivizer.mdl",
        "models/weapons/c_models/c_proto_backpack/c_proto_backpack.mdl",
        "models/weapons/c_models/c_proto_medigun/c_proto_medigun.mdl",
        "models/weapons/c_models/c_proto_medigun/c_proto_medigun_festivizer.mdl",
        "models/weapons/c_models/c_proto_syringegun/c_proto_syringegun.mdl",
        "models/weapons/c_models/c_pyro_arms.mdl",
        "models/weapons/c_models/c_rainblower/c_rainblower.mdl",
        "models/weapons/c_models/c_revolver/c_revolver.mdl",
        "models/weapons/c_models/c_revolver/c_revolver_festivizer.mdl",
        "models/weapons/c_models/c_revolver/c_revolver_xmas.mdl",
        "models/weapons/c_models/c_rocketjumper/c_rocketjumper.mdl",
        "models/weapons/c_models/c_rocketlauncher/c_rocketlauncher.mdl",
        "models/weapons/c_models/c_rocketlauncher/c_rocketlauncher_festivizer.mdl",
        "models/weapons/c_models/c_rocketlauncher/c_rocketlauncher_xmas.mdl",
        "models/weapons/c_models/c_rocketpack/c_rocketpack.mdl",
        "models/weapons/c_models/c_sandwich/c_robo_sandwich.mdl",
        "models/weapons/c_models/c_sandwich/c_sandwich.mdl",
        "models/weapons/c_models/c_sandwich/c_sandwich_xmas.mdl",
        "models/weapons/c_models/c_sapper/c_sapper.mdl",
        "models/weapons/c_models/c_sapper/c_sapper_xmas.mdl",
        "models/weapons/c_models/c_saxxy/c_saxxy.mdl",
        "models/weapons/c_models/c_scattergun.mdl",
        "models/weapons/c_models/c_scattergun/c_scattergun_festivizer.mdl",
        "models/weapons/c_models/c_scattergun/c_scattergun_xmas.mdl",
        "models/weapons/c_models/c_scottish_resistance/c_scottish_resistance.mdl",
        "models/weapons/c_models/c_scottish_resistance/c_scottish_resistance_festivizer.mdl",
        "models/weapons/c_models/c_scout_arms.mdl",
        "models/weapons/c_models/c_shotgun/c_shotgun.mdl",
        "models/weapons/c_models/c_shotgun/c_shotgun_festivizer.mdl",
        "models/weapons/c_models/c_shotgun/c_shotgun_xmas.mdl",
        "models/weapons/c_models/c_shovel/c_shovel.mdl",
        "models/weapons/c_models/c_shovel/c_shovel_festivizer.mdl",
        "models/weapons/c_models/c_slapping_glove/c_slapping_glove.mdl",
        "models/weapons/c_models/c_slapping_glove/w_slapping_glove.mdl",
        "models/weapons/c_models/c_smg/c_smg.mdl",
        "models/weapons/c_models/c_smg/c_smg_festivizer.mdl",
        "models/weapons/c_models/c_smg/c_smg_xmas.mdl",
        "models/weapons/c_models/c_sniper_arms.mdl",
        "models/weapons/c_models/c_sniperrifle/c_sniperrifle.mdl",
        "models/weapons/c_models/c_sniperrifle/c_sniperrifle_festivizer.mdl",
        "models/weapons/c_models/c_sniperrifle/c_sniperrifle_xmas.mdl",
        "models/weapons/c_models/c_soldier_arms.mdl",
        "models/weapons/c_models/c_spy_arms.mdl",
        "models/weapons/c_models/c_sticky_jumper/c_sticky_jumper.mdl",
        "models/weapons/c_models/c_stickybomb_launcher/c_stickybomb_launcher.mdl",
        "models/weapons/c_models/c_stickybomb_launcher/c_stickybomb_launcher_festivizer.mdl",
        "models/weapons/c_models/c_stickybomb_launcher/c_stickybomb_launcher_xmas.mdl",
        "models/weapons/c_models/c_syringegun/c_syringegun.mdl",
        "models/weapons/c_models/c_targe/c_targe.mdl",
        "models/weapons/c_models/c_targe/c_targe_xmas.mdl",
        "models/weapons/c_models/c_tfc_sniperrifle/c_tfc_sniperrifle.mdl",
        "models/weapons/c_models/c_toolbox/c_toolbox.mdl",
        "models/weapons/c_models/c_ubersaw/c_ubersaw.mdl",
        "models/weapons/c_models/c_ubersaw/c_ubersaw_festivizer.mdl",
        "models/weapons/c_models/c_ubersaw/c_ubersaw_xmas.mdl",
        "models/weapons/c_models/c_wooden_bat/c_wooden_bat.mdl",
        "models/weapons/c_models/c_wooden_bat/c_wooden_bat_festivizer.mdl",
        "models/weapons/c_models/c_wrangler.mdl",
        "models/weapons/c_models/c_wrangler_xmas.mdl",
        "models/weapons/c_models/c_wrench/c_wrench.mdl",
        "models/weapons/c_models/c_wrench/c_wrench_festivizer.mdl",
        "models/weapons/c_models/c_wrench/c_wrench_xmas.mdl",
        "models/weapons/c_models/c_xms_double_barrel.mdl",
        "models/weapons/c_models/c_xms_energy_drink/c_xms_energy_drink.mdl",
        "models/weapons/c_models/c_xms_festive_ornament.mdl",
        "models/weapons/c_models/c_xms_flaregun/c_xms_flaregun.mdl",
        "models/weapons/c_models/c_xms_urinejar.mdl",
        "models/weapons/c_models/stattrack.mdl",
        "models/weapons/c_models/urinejar.mdl",

        // workshop c models
        "models/workshop/weapons/c_models/c_acr_hookblade/c_acr_hookblade.mdl",
        "models/workshop/weapons/c_models/c_amputator/c_amputator.mdl",
        "models/workshop/weapons/c_models/c_atom_launcher/c_atom_launcher.mdl",
        "models/workshop/weapons/c_models/c_ava_roseknife/c_ava_roseknife.mdl",
        "models/workshop/weapons/c_models/c_back_scratcher/c_back_scratcher.mdl",
        "models/workshop/weapons/c_models/c_battalion_buffbanner/c_battalion_buffbanner.mdl",
        "models/workshop/weapons/c_models/c_battalion_buffpack/c_battalion_buffpack.mdl",
        "models/workshop/weapons/c_models/c_battalion_bugle/c_battalion_bugle.mdl",
        "models/workshop/weapons/c_models/c_battleaxe/c_battleaxe.mdl",
        "models/workshop/weapons/c_models/c_bazaar_sniper/c_bazaar_sniper.mdl",
        "models/workshop/weapons/c_models/c_bear_claw/c_bear_claw.mdl",
        "models/workshop/weapons/c_models/c_blackbox/c_blackbox.mdl",
        "models/workshop/weapons/c_models/c_blackbox/c_blackbox_xmas.mdl",
        "models/workshop/weapons/c_models/c_bonk_bat/c_bonk_bat.mdl",
        "models/workshop/weapons/c_models/c_boston_basher/c_boston_basher.mdl",
        "models/workshop/weapons/c_models/c_buffalo_steak/c_buffalo_steak.mdl",
        "models/workshop/weapons/c_models/c_buffalo_steak/plate_buffalo_steak.mdl",
        "models/workshop/weapons/c_models/c_caber/c_caber.mdl",
        "models/workshop/weapons/c_models/c_caber/c_caber_exploded.mdl",
        "models/workshop/weapons/c_models/c_candy_cane/c_candy_cane.mdl",
        "models/workshop/weapons/c_models/c_chocolate/c_chocolate.mdl",
        "models/workshop/weapons/c_models/c_chocolate/plate_chocolate.mdl",
        "models/workshop/weapons/c_models/c_claidheamohmor/c_claidheamohmor.mdl",
        "models/workshop/weapons/c_models/c_croc_knife/c_croc_knife.mdl",
        "models/workshop/weapons/c_models/c_crossing_guard/c_crossing_guard.mdl",
        "models/workshop/weapons/c_models/c_crusaders_crossbow/c_crusaders_crossbow.mdl",
        "models/workshop/weapons/c_models/c_crusaders_crossbow/c_crusaders_crossbow_xmas.mdl",
        "models/workshop/weapons/c_models/c_degreaser/c_degreaser.mdl",
        "models/workshop/weapons/c_models/c_degreaser/c_degreaser_pilotlight.mdl",
        "models/workshop/weapons/c_models/c_demo_cannon/c_demo_cannon.mdl",
        "models/workshop/weapons/c_models/c_demo_sultan_sword/c_demo_sultan_sword.mdl",
        "models/workshop/weapons/c_models/c_detonator/c_detonator.mdl",
        "models/workshop/weapons/c_models/c_drg_cowmangler/c_drg_cowmangler.mdl",
        "models/workshop/weapons/c_models/c_drg_manmelter/c_drg_manmelter.mdl",
        "models/workshop/weapons/c_models/c_drg_phlogistinator/c_drg_phlogistinator.mdl",
        "models/workshop/weapons/c_models/c_drg_pomson/c_drg_pomson.mdl",
        "models/workshop/weapons/c_models/c_drg_righteousbison/c_drg_righteousbison.mdl",
        "models/workshop/weapons/c_models/c_drg_thirddegree/c_drg_thirddegree.mdl",
        "models/workshop/weapons/c_models/c_drg_wrenchmotron/c_drg_wrenchmotron.mdl",
        "models/workshop/weapons/c_models/c_dumpster_device/c_dumpster_device.mdl",
        "models/workshop/weapons/c_models/c_eternal_reward/c_eternal_reward.mdl",
        "models/workshop/weapons/c_models/c_eviction_notice/c_eviction_notice.mdl",
        "models/workshop/weapons/c_models/c_fishcake/c_fishcake.mdl",
        "models/workshop/weapons/c_models/c_fishcake/plate_fishcake.mdl",
        "models/workshop/weapons/c_models/c_fists_of_steel/c_fists_of_steel.mdl",
        "models/workshop/weapons/c_models/c_gatling_gun/c_gatling_gun.mdl",
        "models/workshop/weapons/c_models/c_golfclub/c_golfclub.mdl",
        "models/workshop/weapons/c_models/c_ham/c_ham.mdl",
        "models/workshop/weapons/c_models/c_holymackerel/c_holymackerel.mdl",
        "models/workshop/weapons/c_models/c_holymackerel/c_holymackerel_xmas.mdl",
        "models/workshop/weapons/c_models/c_invasion_bat/c_invasion_bat.mdl",
        "models/workshop/weapons/c_models/c_invasion_pistol/c_invasion_pistol.mdl",
        "models/workshop/weapons/c_models/c_invasion_sniperrifle/c_invasion_sniperrifle.mdl",
        "models/workshop/weapons/c_models/c_invasion_wrangler/c_invasion_wrangler.mdl",
        "models/workshop/weapons/c_models/c_iron_curtain/c_iron_curtain.mdl",
        "models/workshop/weapons/c_models/c_jag/c_jag.mdl",
        "models/workshop/weapons/c_models/c_kingmaker_sticky/c_kingmaker_sticky.mdl",
        "models/workshop/weapons/c_models/c_kingmaker_sticky/w_kingmaker_stickybomb.mdl",
        "models/workshop/weapons/c_models/c_letranger/c_letranger.mdl",
        "models/workshop/weapons/c_models/c_liberty_launcher/c_liberty_launcher.mdl",
        "models/workshop/weapons/c_models/c_lochnload/c_lochnload.mdl",
        "models/workshop/weapons/c_models/c_madmilk/c_madmilk.mdl",
        "models/workshop/weapons/c_models/c_mailbox/c_mailbox.mdl",
        "models/workshop/weapons/c_models/c_market_gardener/c_market_gardener.mdl",
        "models/workshop/weapons/c_models/c_medigun_defense/c_medigun_defense.mdl",
        "models/workshop/weapons/c_models/c_medigun_defense/c_medigun_defensepack.mdl",
        "models/workshop/weapons/c_models/c_paintrain/c_paintrain.mdl",
        "models/workshop/weapons/c_models/c_paratooper_pack/c_paratrooper_pack.mdl",
        "models/workshop/weapons/c_models/c_paratooper_pack/c_paratrooper_pack_open.mdl",
        "models/workshop/weapons/c_models/c_paratooper_pack/c_paratrooper_parachute.mdl",
        "models/workshop/weapons/c_models/c_pep_pistol/c_pep_pistol.mdl",
        "models/workshop/weapons/c_models/c_pep_scattergun/c_pep_scattergun.mdl",
        "models/workshop/weapons/c_models/c_persian_shield/c_persian_shield.mdl",
        "models/workshop/weapons/c_models/c_persian_shield/c_persian_shield_all.mdl",
        "models/workshop/weapons/c_models/c_persian_shield/c_persian_shield_arrow.mdl",
        "models/workshop/weapons/c_models/c_persian_shield/c_persian_shield_spike.mdl",
        "models/workshop/weapons/c_models/c_picket/c_picket.mdl",
        "models/workshop/weapons/c_models/c_powerjack/c_powerjack.mdl",
        "models/workshop/weapons/c_models/c_pro_rifle/c_pro_rifle.mdl",
        "models/workshop/weapons/c_models/c_pro_smg/c_pro_smg.mdl",
        "models/workshop/weapons/c_models/c_quadball/c_quadball.mdl",
        "models/workshop/weapons/c_models/c_quadball/w_quadball_grenade.mdl",
        "models/workshop/weapons/c_models/c_reserve_shooter/c_reserve_shooter.mdl",
        "models/workshop/weapons/c_models/c_rfa_hammer/c_rfa_hammer.mdl",
        "models/workshop/weapons/c_models/c_riding_crop/c_riding_crop.mdl",
        "models/workshop/weapons/c_models/c_rift_fire_axe/c_rift_fire_axe.mdl",
        "models/workshop/weapons/c_models/c_rift_fire_mace/c_rift_fire_mace.mdl",
        "models/workshop/weapons/c_models/c_russian_riot/c_russian_riot.mdl",
        "models/workshop/weapons/c_models/c_scatterdrum/c_scatterdrum.mdl",
        "models/workshop/weapons/c_models/c_scimitar/c_scimitar.mdl",
        "models/workshop/weapons/c_models/c_scorch_shot/c_scorch_shot.mdl",
        "models/workshop/weapons/c_models/c_scotland_shard/c_scotland_shard.mdl",
        "models/workshop/weapons/c_models/c_scout_sword/c_scout_sword.mdl",
        "models/workshop/weapons/c_models/c_shortstop/c_shortstop.mdl",
        "models/workshop/weapons/c_models/c_skullbat/c_skullbat.mdl",
        "models/workshop/weapons/c_models/c_sledgehammer/c_sledgehammer.mdl",
        "models/workshop/weapons/c_models/c_snub_nose/c_snub_nose.mdl",
        "models/workshop/weapons/c_models/c_soda_popper/c_soda_popper.mdl",
        "models/workshop/weapons/c_models/c_spikewrench/c_spikewrench.mdl",
        "models/workshop/weapons/c_models/c_sr3_punch/c_sr3_punch.mdl",
        "models/workshop/weapons/c_models/c_switchblade/c_switchblade.mdl",
        "models/workshop/weapons/c_models/c_sydney_sleeper/c_sydney_sleeper.mdl",
        "models/workshop/weapons/c_models/c_tele_shotgun/c_tele_shotgun.mdl",
        "models/workshop/weapons/c_models/c_tele_shotgun/c_tele_shotgun_screen.mdl",
        "models/workshop/weapons/c_models/c_tomislav/c_tomislav.mdl",
        "models/workshop/weapons/c_models/c_trenchgun/c_trenchgun.mdl",
        "models/workshop/weapons/c_models/c_ttg_max_gun/c_ttg_max_gun.mdl",
        "models/workshop/weapons/c_models/c_ttg_sam_gun/c_ttg_sam_gun.mdl",
        "models/workshop/weapons/c_models/c_uberneedle/c_uberneedle.mdl",
        "models/workshop/weapons/c_models/c_unarmed_combat/c_unarmed_combat.mdl",
        "models/workshop/weapons/c_models/c_voodoo_pin/c_voodoo_pin.mdl",
        "models/workshop/weapons/c_models/c_wheel_shield/c_wheel_shield.mdl",
        "models/workshop/weapons/c_models/c_winger_pistol/c_winger_pistol.mdl",
        "models/workshop/weapons/c_models/c_wood_machete/c_wood_machete.mdl",
        "models/workshop/weapons/c_models/c_xms_cold_shoulder/c_xms_cold_shoulder.mdl",
        "models/workshop/weapons/c_models/c_xms_giftwrap/c_xms_giftwrap.mdl",
        "models/workshop/weapons/c_models/c_xms_gloves/c_xms_gloves.mdl",

        // sappers
        "models/buildables/p2rec_placed.mdl",
        "models/buildables/p2rec_placement.mdl",
        "models/buildables/sapper_placed.mdl",
        "models/buildables/sapper_placement.mdl",
        "models/buildables/sapper_xmas_placed.mdl",
        "models/buildables/sapper_xmas_placement.mdl",
        "models/buildables/sd_sapper_placed.mdl",
        "models/buildables/sd_sapper_placement.mdl",

        // canteens
        "models/player/items/mvm_loot/all_class/mvm_flask_ammo.mdl",
        "models/player/items/mvm_loot/all_class/mvm_flask_build.mdl",
        "models/player/items/mvm_loot/all_class/mvm_flask_generic.mdl",
        "models/player/items/mvm_loot/all_class/mvm_flask_krit.mdl",
        "models/player/items/mvm_loot/all_class/mvm_flask_tele.mdl",
        "models/player/items/mvm_loot/all_class/mvm_flask_uber.mdl"
    ));

    public static ArrayList<String> cosmeticModels = new ArrayList<>(Arrays.asList(
        // botkiller fobs
        "models/player/items/mvm_loot/demo/fob_e_stickybomb.mdl",
        "models/player/items/mvm_loot/demo/fob_h_stickybomb.mdl",
        "models/player/items/mvm_loot/demo/fob_h_stickybomb_diamond.mdl",
        "models/player/items/mvm_loot/engineer/fob_e_wrench.mdl",
        "models/player/items/mvm_loot/engineer/fob_h_wrench.mdl",
        "models/player/items/mvm_loot/engineer/fob_h_wrench_diamond.mdl",
        "models/player/items/mvm_loot/heavy/fob_e_minigun.mdl",
        "models/player/items/mvm_loot/heavy/fob_h_minigun.mdl",
        "models/player/items/mvm_loot/heavy/fob_h_minigun_diamond.mdl",
        "models/player/items/mvm_loot/medic/fob_e_medigun.mdl",
        "models/player/items/mvm_loot/medic/fob_h_medigun.mdl",
        "models/player/items/mvm_loot/medic/fob_h_medigun_diamond.mdl",
        "models/player/items/mvm_loot/pyro/fob_e_flamethrower.mdl",
        "models/player/items/mvm_loot/pyro/fob_e_flamethrower_v.mdl",
        "models/player/items/mvm_loot/pyro/fob_h_flamethrower.mdl",
        "models/player/items/mvm_loot/pyro/fob_h_flamethrower_diamond.mdl",
        "models/player/items/mvm_loot/pyro/fob_h_flamethrower_diamond_v.mdl",
        "models/player/items/mvm_loot/pyro/fob_h_flamethrower_v.mdl",
        "models/player/items/mvm_loot/scout/fob_e_scattergun.mdl",
        "models/player/items/mvm_loot/scout/fob_h_scattergun.mdl",
        "models/player/items/mvm_loot/scout/fob_h_scattergun_diamond.mdl",
        "models/player/items/mvm_loot/sniper/fob_e_sniperrifle.mdl",
        "models/player/items/mvm_loot/sniper/fob_h_sniperrifle.mdl",
        "models/player/items/mvm_loot/sniper/fob_h_sniperrifle_diamond.mdl",
        "models/player/items/mvm_loot/soldier/fob_e_rocketlauncher.mdl",
        "models/player/items/mvm_loot/soldier/fob_h_rocketlauncher.mdl",
        "models/player/items/mvm_loot/soldier/fob_h_rocketlauncher_diamond.mdl",
        "models/player/items/mvm_loot/spy/fob_e_knife.mdl",
        "models/player/items/mvm_loot/spy/fob_h_knife.mdl",
        "models/player/items/mvm_loot/spy/fob_h_knife_diamond.mdl",

        // items
        "models/workshop/player/items/demo/bagpipes/bagpipes.mdl",
        "models/workshop/player/items/demo/demo_booties/demo_booties.mdl",
        "models/workshop/player/items/demo/pegleg/pegleg.mdl",
        "models/workshop/player/items/engineer/bucking_bronco/bucking_bronco.mdl",
        "models/workshop/player/items/pyro/ghost_aspect/ghost_aspect.mdl",
        "models/workshop/player/items/pyro/pyro_halloween_gasmask/pyro_halloween_gasmask.mdl",
        "models/workshop/player/items/pyro/spring_rider/spring_rider.mdl",
        "models/workshop/player/items/pyro/threea_nabler/threea_nabler.mdl",
        "models/workshop/player/items/sniper/croc_shield/croc_shield.mdl",
        "models/workshop/player/items/sniper/killer_solo/killer_solo.mdl",
        "models/workshop/player/items/sniper/xms_sniper_commandobackpack/xms_sniper_commandobackpack.mdl",
        "models/workshop/player/items/soldier/fumblers_fanfare/fumblers_fanfare.mdl",
        "models/workshop/player/items/soldier/mantreads/mantreads.mdl",

        // misc
        "models/player/items/all_class/drg_badge.mdl",
        "models/player/items/all_class/hwn_spellbook_complete.mdl",
        "models/player/items/all_class/hwn_spellbook_diary.mdl",
        "models/player/items/all_class/ring_demo.mdl",
        "models/player/items/all_class/ring_Engineer.mdl",
        "models/player/items/all_class/ring_Heavy.mdl",
        "models/player/items/all_class/ring_Medic.mdl",
        "models/player/items/all_class/ring_Pyro.mdl",
        "models/player/items/all_class/ring_Scout.mdl",
        "models/player/items/all_class/ring_Sniper.mdl",
        "models/player/items/all_class/ring_Soldier.mdl",
        "models/player/items/all_class/ring_Spy.mdl",
        "models/player/items/crafting/coin_invasion.mdl",
        "models/player/items/crafting/coin_summer2015_bronze.mdl",
        "models/player/items/crafting/coin_summer2015_gold.mdl",
        "models/player/items/crafting/coin_summer2015_gravel.mdl",
        "models/player/items/crafting/coin_summer2015_silver.mdl",
        "models/player/items/crafting/community_cosmetic_case.mdl",
        "models/player/items/crafting/cosmetic_case.mdl",
        "models/player/items/crafting/cosmetic_case_ribbon.mdl",
        "models/player/items/crafting/halloween_case.mdl",
        "models/player/items/crafting/halloween2015_case.mdl",
        "models/player/items/crafting/stamp_winter2016.mdl",
        "models/player/items/crafting/weapons_case.mdl",
        "models/player/items/cyoa_pda/cyoa_pda.mdl",
        "models/player/items/demo/crown.mdl",
        "models/player/items/engineer/guitar.mdl",
        "models/workshop/player/items/all_class/secondrate_sorcery/secondrate_sorcery_demo.mdl",
        "models/workshop/player/items/all_class/zoomin_broom/zoomin_broom_demo.mdl"
    ));

    public static ArrayList<String> buildingModels = new ArrayList<>(Arrays.asList(
        "models/buildables/dispenser.mdl",
        "models/buildables/dispenser_lvl2.mdl",
        "models/buildables/dispenser_lvl3.mdl",
        "models/buildables/sentry1.mdl",
        "models/buildables/sentry1_heavy.mdl",
        "models/buildables/sentry2.mdl",
        "models/buildables/sentry2_heavy.mdl",
        "models/buildables/sentry3.mdl",
        "models/buildables/sentry3_heavy.mdl",
        "models/buildables/sentry3_rockets.mdl",
        "models/buildables/teleporter.mdl",
        "models/buildables/teleporter_blueprint_enter.mdl",
        "models/buildables/teleporter_blueprint_exit.mdl"
    ));

    public static ArrayList<String> breadModels = new ArrayList<>(Arrays.asList(
        "models/weapons/c_models/c_bread/c_bread_baguette.mdl",
        "models/weapons/c_models/c_bread/c_bread_burnt.mdl",
        "models/weapons/c_models/c_bread/c_bread_cinnamon.mdl",
        "models/weapons/c_models/c_bread/c_bread_cornbread.mdl",
        "models/weapons/c_models/c_bread/c_bread_crumpet.mdl",
        "models/weapons/c_models/c_bread/c_bread_plainloaf.mdl",
        "models/weapons/c_models/c_bread/c_bread_pretzel.mdl",
        "models/weapons/c_models/c_bread/c_bread_ration.mdl",
        "models/weapons/c_models/c_bread/c_bread_russianblack.mdl",
        "models/weapons/w_models/w_breadmonster/w_breadmonster.mdl",
        "models/weapons/c_models/c_breadmonster/c_breadmonster.mdl",
        "models/weapons/c_models/c_breadmonster/c_breadmonster_milk.mdl",
        "models/weapons/c_models/c_breadmonster_gloves/c_breadmonster_gloves.mdl",
        "models/weapons/c_models/c_breadmonster_sapper/c_breadmonster_sapper.mdl"
    ));

    public static ArrayList<String> pickupsAndFunGibModels = new ArrayList<>(Arrays.asList(
        "models/items/ammopack_large.mdl",
        "models/items/ammopack_large_bday.mdl",
        "models/items/ammopack_medium.mdl",
        "models/items/ammopack_medium_bday.mdl",
        "models/items/ammopack_small.mdl",
        "models/items/banana/plate_banana.mdl",
        "models/items/currencypack_large.mdl",
        "models/items/currencypack_medium.mdl",
        "models/items/currencypack_small.mdl",
        "models/items/festivizer.mdl",
        "models/items/gift_festive.mdl",
        "models/items/medkit_large.mdl",
        "models/items/medkit_large_bday.mdl",
        "models/items/medkit_medium.mdl",
        "models/items/medkit_medium_bday.mdl",
        "models/items/medkit_small.mdl",
        "models/items/paintkit_tool.mdl", //TESTME
        "models/items/plate.mdl",
        "models/items/plate_robo_sandwich.mdl",
        "models/items/plate_sandwich_xmas.mdl",
        "models/passtime/ball/passtime_ball.mdl",
        "models/player/gibs/gibs_balloon.mdl",
        "models/player/gibs/gibs_bolt.mdl",
        "models/player/gibs/gibs_boot.mdl",
        "models/player/gibs/gibs_burger.mdl",
        "models/player/gibs/gibs_can.mdl",
        "models/player/gibs/gibs_clock.mdl",
        "models/player/gibs/gibs_fish.mdl",
        "models/player/gibs/gibs_gear1.mdl",
        "models/player/gibs/gibs_gear2.mdl",
        "models/player/gibs/gibs_gear3.mdl",
        "models/player/gibs/gibs_gear4.mdl",
        "models/player/gibs/gibs_gear5.mdl",
        "models/player/gibs/gibs_hubcap.mdl",
        "models/player/gibs/gibs_licenseplate.mdl",
        "models/player/gibs/gibs_spring1.mdl",
        "models/player/gibs/gibs_spring2.mdl",
        "models/player/gibs/gibs_teeth.mdl",
        "models/player/gibs/gibs_tire.mdl",
        "models/player/gibs/random_organ.mdl",
        "models/player/gibs/random_organ.mdl",
        "models/workshop/cases/invasion_case/invasion_case.mdl",
        "models/workshop/cases/invasion_case/invasion_case_rare.mdl",
        "models/weapons/w_models/w_toolbox.mdl"
    ));

    public static ArrayList<String> projectileModels = new ArrayList<>(Arrays.asList(
        "models/weapons/w_models/w_arrow.mdl",
        "models/weapons/w_models/w_arrow_xmas.mdl",
        "models/weapons/w_models/w_baseball.mdl",
        "models/weapons/w_models/w_cannonball.mdl",
        "models/weapons/w_models/w_cigarette_case.mdl",
        "models/weapons/w_models/w_drg_ball.mdl",
        "models/weapons/w_models/w_flaregun_shell.mdl",
        "models/weapons/w_models/w_grenade_grenadelauncher.mdl",
        "models/weapons/w_models/w_grenadelauncher.mdl",
        "models/weapons/w_models/w_repair_claw.mdl",
        "models/weapons/w_models/w_rocket.mdl",
        "models/weapons/w_models/w_rocket_airstrike/w_rocket_airstrike.mdl",
        "models/weapons/w_models/w_stickybomb.mdl",
        "models/weapons/w_models/w_stickybomb_d.mdl",
        "models/weapons/w_models/w_stickybomb2.mdl",
        "models/weapons/w_models/w_syringe_proj.mdl",
        "models/workshop/weapons/c_models/c_crusaders_crossbow/c_crusaders_crossbow_xmas_proj.mdl"
    ));

    public static ArrayList<String> weaponsThatTurnToGold = new ArrayList<>(Arrays.asList(
        "models/weapons/c_models/c_saxxy/c_saxxy.mdl"
    ));

    /**
     * Gets a random model using the defined lists, which have their own weights
     * @return The random model chosen
     */
    public static String getRandomModel() {
        ArrayList<WeightedItem<ArrayList<String>>> weightedItems = new ArrayList<>(Arrays.asList(
            new WeightedItem<>(weaponModels, 100),
            new WeightedItem<>(cosmeticModels, 100),
            new WeightedItem<>(breadModels, 200),
            new WeightedItem<>(pickupsAndFunGibModels, 200),
            new WeightedItem<>(projectileModels, 150),
            new WeightedItem<>(buildingModels, 80)
        ));

        WeightedItemCollection<ArrayList<String>> collection = new WeightedItemCollection<>(weightedItems);
        return PopRandomizer.randomElement(collection.getRandomItem());
    }
}
