package Pop.Bot.Cosmetics;

import java.util.ArrayList;
import java.util.Arrays;

/**
 * Contains various lists of things that apply to all classes
 */
public class AllClassCosmeticLists {
    /**
     * All-class cosmetics
     */
    public final static ArrayList<Cosmetic> cosmetics = new ArrayList<>(
        Arrays.asList(
            new Cosmetic("Honest Halo"),
            new Cosmetic("Ghastly Gibus", "Ghastlierest Gibus"),
            new Cosmetic("Ghastly Gibus 2010", "Ghastlier Gibus"),
            new Cosmetic("Ghastly Gibus 2011", "Ghastly Gibus"),
            new Cosmetic( "Ghostly Gibus"),
            new Cosmetic( "The Galvanized Gibus"),
            new Cosmetic("Mildly Disturbing Halloween Mask", "Mildly Disturbing"),
            new Cosmetic("L4D Hat"),
            new Cosmetic( "Modest Pile of Hat"),
            new Cosmetic("Noble Amassment of Hats"),
            new Cosmetic("Towering Pillar of Hats"),
            new Cosmetic("Propaganda Contest Third Place", "Third Place"),
            new Cosmetic("Propaganda Contest Second Place", "Second Place"),
            new Cosmetic("Propaganda Contest First Place", "First Place"),
            new Cosmetic("TTG Max Hat"),
            new Cosmetic("OSX Item"),
            new Cosmetic("Parasite Hat"),
            new Cosmetic("Wiki Cap"),
            new Cosmetic("Ellis Hat"),
            new Cosmetic("Mann Co. Cap"),
            new Cosmetic("Dr's Dapper Topper"),
            new Cosmetic("Halloween Mask - Scout", "Halloween Scout"),
            new Cosmetic("Halloween Mask - Sniper", "Halloween Sniper"),
            new Cosmetic("Halloween Mask - Soldier", "Halloween Soldier"),
            new Cosmetic("Halloween Mask - Demoman", "Halloween Demoman"),
            new Cosmetic("Halloween Mask - Medic", "Halloween Medic"),
            new Cosmetic("Halloween Mask - Heavy", "Halloween Heavy"),
            new Cosmetic("Halloween Mask - Spy", "Halloween Spy"),
            new Cosmetic("Halloween Mask - Engineer", "Halloween Engineer"),
            new Cosmetic("Halloween Mask - Pyro", "Halloween Pyro"),
            new Cosmetic("Halloween Mask - Saxton Hale", "Halloween Saxton"),
            new Cosmetic("Horrific Headsplitter"),
            new Cosmetic("Horseless Headless Horseman's Head", "Horseman's Head"),
            new Cosmetic("Spine-Chilling Skull"),
            new Cosmetic("Voodoo Juju"),
            new Cosmetic("Treasure Hat 1", "Bountiful"),
            new Cosmetic("Treasure Hat 2", "Treasure"),
            new Cosmetic("Treasure Hat 3", "Undeniably Wealthy"),
            new Cosmetic("A Rather Festive Tree", "A Rather Festive"),
            new Cosmetic("World Traveler"),
            new Cosmetic("MNC Hat"),
            new Cosmetic("Humanitarian's Hachimaki"),
            new Cosmetic("Benefactor's Kanmuri"),
            new Cosmetic("Mangnanimous Monarch"),
            new Cosmetic("Potato Hat"),
            new Cosmetic("Camera Helm"),
            new Cosmetic("Lo-Fi Longwave"),
            new Cosmetic("Spiral Sallet"),
            //"Friendly Item",
            new Cosmetic("Loyalty Reward"),
            new Cosmetic("Summer Hat"),
            new Cosmetic("Summer Shades"),
            new Cosmetic("The Sarif Cap"),
            new Cosmetic("The Deus Specs"),
            new Cosmetic("TF Birthday Hat 2011", "Party Hat"),
            new Cosmetic("Killer Exclusive"),
            new Cosmetic("Manniversary Paper Hat", "Paper Hat"),
            new Cosmetic("The Hot Dogger"),
            new Cosmetic("The Salty Dog"),
            new Cosmetic("MONOCULUS!"),
            new Cosmetic("Seal Mask"),
            new Cosmetic("Point and Shoot"),
            new Cosmetic("The Top Notch"),
            new Cosmetic("The B.M.O.C."),
            new Cosmetic("The Brown Bomber"),
            new Cosmetic("The Ebenezer"),
            new Cosmetic("The Full Head of Steam"),
            new Cosmetic("The Holiday Headcase"),
            new Cosmetic("The Warsworn Helmet"),
            new Cosmetic("The Bolt Action Blitzer"),
            new Cosmetic("The Gentle Munitionne of Leisure"),
            new Cosmetic("Autogrant Pyrovision Goggles", "Pyrovision"),
            new Cosmetic("Robot Chicken Hat"),
            new Cosmetic("The Human Cannonball"),
            new Cosmetic("Promo Marxman"),
            new Cosmetic("Pet Robro"),
            new Cosmetic("The Crone's Dome"),
            new Cosmetic("The Executioner"),
            new Cosmetic("The Skull Island Topper"),
            new Cosmetic("That '70s Chapeau"),
            new Cosmetic("The Cockfighter"),
            new Cosmetic("Antlers"),
            new Cosmetic("Mann Co. Online Cap"),
            new Cosmetic("Tough Stuff Muffs"),
            new Cosmetic("The Brutal Bouffant"),
            new Cosmetic("The TF2VRH", "VR"),
            new Cosmetic("The Conspiracy Cap"),
            new Cosmetic("The Public Accessor"),
            new Cosmetic("Modest Metal Pile of Scrap", "Pile of Scrap"),
            new Cosmetic("Noble Nickel Amassment of Hats", "Amassment of Hats"),
            new Cosmetic("Towering Titanium Pillar of Hats", "Pillar of Hats"),
            new Cosmetic("The Bot Dogger"),
            new Cosmetic("The Brotherhood of Arms"),
            new Cosmetic("The Well-Rounded Rifleman"),
            new Cosmetic("The Hardy Laurel"),
            new Cosmetic("Graybanns"),
            new Cosmetic("The Virtual Viewfinder"),
            new Cosmetic("The Federal Casemaker"),
            new Cosmetic("The Grandmaster"),
            new Cosmetic("The Cotton Head"),
            new Cosmetic("Hong Kong Cone"),
            new Cosmetic("The Birdie Bonnet"),
            new Cosmetic("The Dark Helm"),
            new Cosmetic("The Haunted Hat"),
            new Cosmetic("The Magical Mercenary"),
            new Cosmetic("The Manneater"),
            new Cosmetic("The One-Way Ticket"),
            new Cosmetic("The Tuque or Treat"),
            new Cosmetic("The Kiss King"),
            new Cosmetic("Neckwear Headwear"),
            new Cosmetic("The Polar Pullover"),
            new Cosmetic("The Dictator"),
            new Cosmetic("The Law"),
            new Cosmetic("The Mustachioed Mann"),
            new Cosmetic("The Dark Falkirk Helm"),
            new Cosmetic("Towering Pillar of Summer Shades", "Pillar of Shades"),
            new Cosmetic("Horace"),
            new Cosmetic("The MK 50"),
            new Cosmetic("The Dadliest Catch"),
            new Cosmetic("Brimstone"),
            new Cosmetic("The Crown of the Old Kingdom", "Crown"),
            new Cosmetic("The Tomb Readers"),
            new Cosmetic("EOTL_FURCAP", "Fur Cap"),
            new Cosmetic("EOTL_Brisk-weather Beanie", "Brick Weather Beanie"),
            new Cosmetic("EOTL_hiphunter_hat", "Hip Hunger Hat"),
            new Cosmetic("dec2014 CoPilot_2014", "Co-Pilot"),
            new Cosmetic("The Finder's Fee"),
            new Cosmetic("Captain Cardbeard Cutthroat", "Cutthroat"),
            new Cosmetic("The Rotation Sensation"),
            new Cosmetic("Potassium Bonnett"),
            new Cosmetic("Captain Space Mann"),
            new Cosmetic("Phononaut"),
            new Cosmetic("Universal Translator"),
            new Cosmetic("Duck Billed Hatypus"),
            //"Prehistoric Pullover", // Glitchy looking
            new Cosmetic("Arkham Cowl"),
            new Cosmetic("A Well Wrapped Hat", "A Well Wrapped"),
            new Cosmetic("The Chill Chullo"),
            new Cosmetic("The Patriot Peak"),
            new Cosmetic("Bedouin Bandana"),
            new Cosmetic("Prinny Hat"),
            new Cosmetic("Civilian Grade JACK Hat", "Civilian Grade"),
            new Cosmetic("Jaunty Trailblazer 2016", "Jaunty Trailblazer"),
            new Cosmetic("Class Crown"),
            new Cosmetic("Lil' Bitey"),
            new Cosmetic("Nasty Norsemann"),
            new Cosmetic("Spooktacles"),
            new Cosmetic("The Toadstool Topper"),
            new Cosmetic("Unusual Cap"),
            new Cosmetic("The Head Prize"),
            new Cosmetic("The Snowmann"),
            new Cosmetic("Woolen Warmer"),
            new Cosmetic("The Audio File"),
            new Cosmetic("The Aztec Warrior"),
            new Cosmetic("The Hunter in Darkness"),
            new Cosmetic("Jungle Wreath"),
            new Cosmetic("Yeti Park Cap"),
            new Cosmetic("The Pithy Professional"),
            new Cosmetic("Saxton Hat"),
            new Cosmetic("The Caribou Companion"),
            new Cosmetic("The Tundra Top"),
            new Cosmetic("Deadbeats", "Deadbeat"),
            new Cosmetic("Lucky Cat Hat"),
            new Cosmetic("Terror-antula"),
            new Cosmetic("Bread Heads"),
            new Cosmetic("Pocket Admin"),
            new Cosmetic("The Polar Pal"),
            new Cosmetic("Stapler's Specs"),
            new Cosmetic("Bat Hat"),
            new Cosmetic("Binoculus"),
            new Cosmetic("The Horrible Horns", "Horrible Horned"),
            new Cosmetic("Mister Bones"),
            new Cosmetic("Pocket Halloween Boss", "Halloween Boss"),
            new Cosmetic("Bumble Beenie"),
            new Cosmetic("Candy Crown"),
            new Cosmetic("Citizen Cane"),
            new Cosmetic("Gingerbread Mann"),
            new Cosmetic("Glittering Garland"),
            new Cosmetic("Globetrotter"),
            new Cosmetic("Pebbles the Penguin"),
            new Cosmetic("Smissmas Saxton"),
            new Cosmetic("Yule Hog"),
            new Cosmetic("Breadcrab"),
            new Cosmetic("Hypno-eyes"),
            new Cosmetic("A Handsome Handy Thing", "Handy"),
            new Cosmetic("All Hallows' Hatte", "All Hallows'"),
            new Cosmetic("Balloonicorpse"),
            new Cosmetic("Eye-see-you", "Eye-See-You"),
            new Cosmetic("Handsome Devil"),
            new Cosmetic("Hollowed Helm"),
            new Cosmetic("Impish Ears"),
            new Cosmetic("King Cardbeard"),
            new Cosmetic("Misfortune Fedora"),
            new Cosmetic("Sir Pumpkinton"),
            new Cosmetic("Wrap-A-Khamon"),
            new Cosmetic("Candy Cantlers"),
            new Cosmetic("Festive Fascinator"),
            new Cosmetic("Jolly Jingler"),
            new Cosmetic("Professional's Pom Pom", "Pom Pom"),
            new Cosmetic("Reindoonibeanie"),
            new Cosmetic("Shoestring Santa"),
            new Cosmetic("The Smissmass Sorcerer", "Smissmas Sorcerer"),
            new Cosmetic("Towering Pile Of Presents", "Pile of Presents"),
            new Cosmetic("Towering Pillar of Beanies", "Pillar of Beanies"),
            new Cosmetic("Ballooniphones"),
            new Cosmetic("Alakablamicon"),
            new Cosmetic("Beanie The All-Gnawing", "All-Gnawing"),
            new Cosmetic("The Bone Cone"),
            new Cosmetic("Creepy Crawlers", "Creepy Crawler"),
            new Cosmetic("Eyequarium"),
            new Cosmetic("Goalkeeper"),
            new Cosmetic("Hat Outta Hell"),
            new Cosmetic("The Scariest Mask EVER", "The Scariest"),
            new Cosmetic("Second-head Headwear", "Second-head"),
            new Cosmetic("Spooky Head-Bouncers"),
            new Cosmetic("Towering Patch of Pumpkins", "Towering Pumpkins"),
            new Cosmetic("Twisted Topper"),
            new Cosmetic("Brain Cane"),
            new Cosmetic("Cozy Catchers"),
            new Cosmetic("Cozy Catchers"),
            new Cosmetic("El Fiestibrero"),
            new Cosmetic("Elf-Made Bandanna"),
            new Cosmetic("Festive Frames"),
            new Cosmetic("The Giftcrafter"),
            new Cosmetic("Gnome Dome"),
            new Cosmetic("Hat Chocolate"),
            new Cosmetic("Jolly Jester"),
            new Cosmetic("Merry Cone"),
            new Cosmetic("Oh Deer!", "Oh Deer"),
            new Cosmetic("Ominous Offering"),
            new Cosmetic("Reindoonihorns"),
            new Cosmetic("Seasonal Spring")
        )
    );
}
